### ISSUE TITLE
Couple Issues with ores and tinkers construct compatibility 

### ISSUE THREAD

**Issue by InkDragon** [SmithsGaming/Armory#11]
First off when mining multiple types of ore added by armory-world they all assume they are the first type.
Example: If you mine 3 copper ore, then mine 2 silver/lead/tin you will end up with 5 copper ore.

second issue is that lead and silver ore wont melt in either a tinkers' smeltery or a tsteelworks' high oven. Copper and Tin work fine however

third and final issue is that Armory-Weaponry doesn't add copper or tin armors despite both being found in TiCon, and no config files are found for steel despite it being armor when tsteelworks is also loaded.

**Comment by marchermans** [comment]
I am looking into that issue with the mining, noticed it myself couple of days ago while testing, but we are working on some changes in the API so i have to wait until those are actually done, should not take too long though.

For the not smelting in the Smeltery: I will take a look at that, i have them registered properly and it worked when i tested it before release, what version of TiC are you using?

It is indeed correct that Armory-Weaponry does not add the the Copper and Tin armors, as Armory-World adds them (for now). We are working on a system (for which the API Changes are, that put fixes on hold) that enables the automated mapping of materials from the TiC Registry to the Armory MaterialRegistry, but to develop this takes time, as i need a system that can create Colored ToolTips outside of the active range of Colors that normal Vanilla provides. 

I have an Exam on friday and after that i will probably have time to finish the new ToolTip rendering pipeline for Armory. The rest is already updated internally and is ready to be released, I will fix your bugs in one go then with the release as well.

Greets,
Orion

**Comment by InkDragon** [comment]
latest version of TiC from Curse(1.8.5), and the latest jenkins build of tsteelworks (http://tehnut.info/jenkins/job/TSteelworks/16/)

I hope you do well on your exam, no rush to fix stuff, just wanted to make sure you knew about it so you can fix it when you have time.

**Comment by marchermans** [comment]
Yeah, study comes first currently. Slowly making progress when I have the time todo so.

**Comment by marchermans** [comment]
Okey i fixed the issues. Try updating Armory-World-1.0.0-19. You will also need Armory 1.0.0-175 to run that world version.
