### ISSUE TITLE
Remove the need for tings when crafting Rings from Nuggets

### ISSUE THREAD

**Issue by kutschkem** [SmithsGaming/Armory#16]
How are you supposed to start this mod? A little documentation would help. I managed to get Iron Nuggets, now I am stuck at trying to get tongs. To craft them, you need an iron ring, but to craft the ring, you need tongs?!

Is there something I am doing wrong, or is this progression somehow broken?

**Comment by marchermans** [comment]
You are completely right, i am sorry we updated the crafting routines for the next update and while fixing some bugs that has slipped through the cracks. I will push out an update over the next couple of days containing all the fixes including one for this one.

**Comment by marchermans** [comment]
Fixed in Release 1.0.1.
Use version 1.0.1.3 - 191 and up.

**Comment by kutschkem** [comment]
When do you plan to release it on curse?

**Comment by marchermans** [comment]
It is on Curse, check out Armory - Armoring the world.

**Comment by marchermans** [comment]
I think the current version is 197
