### ISSUE TITLE
Umm I broke something...

### ISSUE THREAD

**Issue by jonathen-akens** [SmithsGaming/Armory#17]
I was loading a server for the first time and doing some testing. These mods worked in SSP but when i was loading on a server i get this crash: http://pastebin.com/1anhv3Lq
the mod looks great and i cant wait for it to reach its fully fleshed out version. Thanks :smile:

**Comment by marchermans** [comment]
Hai, we noticed that too. During the last release we forgot to remove a tag on a class, which makes it now missing... sadly.

We are nearly done with the changes to the firepit and have that bug already fix and ready for the next release. I am having some exams coming up, so development has to slow down a bit, yet i will release a new version somewhere sunday that includes all the changes, including the bugfix.

This means that for now, colors will not sync between server and client, yet all other properties will.

I am not home currently so I cannot release the fix until when i am back.

Orion

**Comment by marchermans** [comment]
To release a fix for this is going to take a little bit longer. We are finishing up and polishing some of the last details (like the Item Rendering for the new Block Models, and stuff) hope to release today or tomorrow

**Comment by marchermans** [comment]
Fixed in Release 1.0.1.
Use version 1.0.1.3 - 191 and up.
