### ISSUE TITLE
Add nuggets to ore dictionary

### ISSUE THREAD

**Issue by kutschkem** [SmithsGaming/Armory#19]
Your nuggets are not registered in the ore dictionary. That breaks all recipes that require things like iron nuggets, because the "normal" way of obtaining nuggets is removed by Armory.

**Comment by marchermans** [comment]
The nuggets are succesfully being registered to the OreDic.
Tested it with version 1.0.1.3-197.

Can you send me some pictures of your problems, and a log would be nice.

**Comment by kutschkem** [comment]
![image](https://cloud.githubusercontent.com/assets/1106888/8895221/910540a6-33d1-11e5-88d0-a1e3ebac147a.png)

Screenshot of my OreDict dump. I use version 197 as well. As you see, no Armory nugget. What log would you like?

**Comment by marchermans** [comment]
I donnot need a log, that is actually all i need. I will do some digging why it might not register....

**Comment by marchermans** [comment]
Okey, i might have an idea why this is happening, yet a sulotion has to wait until the Knowledge Update.
For now, disable hardmode in the Global.cfg (Can be found under {minecraft dir}/config/Armory), it reactivates the nuggets of the other mods.
