### ISSUE TITLE
Server Glitches

### ISSUE THREAD

**Issue by PrettyHeatToast** [SmithsGaming/Armory#24]
-The burnpit crashes the server and dupes.
-The anvil kicks you from the server and dupes.

**Comment by marchermans** [comment]
You are going to need to be more specific.....

We have a test server on which we test our builds and on there Armory does not have those issues.

So regarding the FirePit, i am going to need the crashlog, regarding the Anvil i am going to need some extra details regarding what you where doing? And what the messages are?

Orion

**Comment by marchermans** [comment]
@PrettyHeatToast I am more than happy to fix the Issues, but i will need some more info before i can doi that.

Do you have a central place were you get reports from you ModPack?

**Comment by PrettyHeatToast** [comment]
There seems to be some inconsistency with these issues so I'm going to test a bit more on my end.
Sorry for the late response.

**Comment by marchermans** [comment]
Cool, if you need any tools from my side to test this, just give me a ping here i will try to put them in teh next release of Armory yet this has to wait untill i fix the GUI Design Problem (I am still in the unclear how todo the Book Binders UI)

**Comment by Tim020** [comment]
We could always put a patch in place from a previous commit if needed :)

**Comment by OrionDevelopment** [comment]
We could? I tried that last time, So it would be awesome if you could tell me how!

**Comment by Tim020** [comment]
Checkout the commit you want, fork the repo at that point; and then rebase rather than merge when done :)

**Comment by OrionDevelopment** [comment]
Are you able to join me later tonight?

**Comment by Tim020** [comment]
Will do when I'm home from work - finish in an hour

**Comment by OrionDevelopment** [comment]
Awesome, will delete this comment spam now (as soon as you write oke)

**Comment by Tim020** [comment]
Oke! :)

**Comment by PrettyHeatToast** [comment]
As it turns out, only the firpit has issues but the anvil also crashed because it was next to the firepit.
The crashreport after updating the firepit block: http://pastebin.com/BJMcPT9s
-Thanks in advance and you did a great job on this mod.

**Comment by marchermans** [comment]
I fixed this already :D, Yet @Tim020 did not tell me how to merge the fix back in so it is currently waiting for release.... I have big parts of the new UI System done and all the Blueprints are generating, Just need to finish up the Book Binder and i will release a new version, which will be hopefully if i get the time somewhere next week.

If @Tim020  is willing and able to tell me how to insert a fix in the Branch i will update before i go away this weekend but i cannot make that promise.

**Comment by marchermans** [comment]
The error should only happen on dedicated servers though

**Comment by PrettyHeatToast** [comment]
Thanks for fixing it so soon, I will eagerly await the next update.

**Comment by marchermans** [comment]
Believe me, the mod will get a tiny bit harder and much better to follow once i am done.

Bet a little teaser might not be bad: http://gfycat.com/PracticalOrderlyDrafthorse

**Comment by PrettyHeatToast** [comment]
That looks very intresting!

**Comment by marchermans** [comment]
That was the state roughly 2 weeks ago, we are currently working on the BookBinder, ones it functionality is done we will release a new version, and then start the work on the UI of the book

**Comment by marchermans** [comment]
New release is coming wit a big fix, would you try the new Alpha Release #229?

**Comment by PrettyHeatToast** [comment]
The new version doesn't seem to have any issues, thanks for fixing it.

**Comment by marchermans** [comment]
Cool.
