### ISSUE TITLE
Freeze, Had to manual crash

### ISSUE THREAD

**Issue by Dragnier** [SmithsGaming/Armory#30]
Here is what the console said errored when I crashed the game manually: https://gist.github.com/Dragnier/eca20fb797a43224ba7148767c189f73

**Comment by marchermans** [comment]
Thanks for the report found the issue, seems that I forgot to push a fix for that bug when I did the restructure.

I will make one a soon as I am home an have a couple I minutes, however I can only make one for MC version 1.10.2 as development on 1.9 has been halted. If you cannot upgrade to 1.10 then I suggest to turn off hard mode (aka nugget recipe removal) in armories global configuration, this should prevent this crash from happening.

**Comment by marchermans** [comment]
Sorry for the typos I am on my phone

**Comment by Dragnier** [comment]
I'm using 1.10.2; most 1.9.4 mods that haven't been updated yet actually load in 1.10.2 just fine. That's why you see a few of them. Any mod, like yours, which is updated to 1.10.2 officially is using the proper file.

**Comment by marchermans** [comment]
Here you go, there should be a new build in arround 20 Minutes.

**Comment by marchermans** [comment]
New build is live!
