### ISSUE TITLE
Crash when placing Forge

### ISSUE THREAD

**Issue by Drakoflame** [SmithsGaming/Armory#32]
http://pastebin.com/gqSpejBb

Its me again... you guys must be starting to hate seeing me > 3> always breaking your toys, making you work harder... but at the same time I'm that one in a million kinda guy that ALWAYS gets every crash.... that and I stress test with other mods XD

this time the game only crashed when I put down an anvil (so yay! the custom smith'score worked :D)

Also, I wasn't able to find a recipe for the stone blacksmiths anvil, which I would have needed to make a fireplace, as the forge is now crafted with heated components, I just put it down because I wanted to see if I could craft chain links and stuff, like I was unable to in the 1.7.10 version XD

**Comment by marchermans** [comment]
There is no REcipe for the Stone Anvil..... Try rightclicking the middle block of a 3x3x3 of cobblestone with a blacksmiths anvil.... Magic.

And please remove the Shader. That shader is not compatible with Forge it seems as it changes the render pipeline. I will check with the other guys to see what the issue is there.

**Comment by marchermans** [comment]
So yeah i checked with the guys, they think the RenderPipeline is being changed by that Shader in a way that is just not compatible, or i would need to rename the property, cause something else standardly creates a property with the name burning but it is not a Bool....... Which is highly unlikely but i can try.

**Comment by marchermans** [comment]
I added not supported for now as this is not a default behaviour. I will however try to help you fix this issue. But my CI System is broken right now so i cannot get a new build out that quickly.

**Comment by marchermans** [comment]
I uploaded a new Version of Armory to Curse, it has a different property name, if it still crashes then one of your coremods is doing something horribly wrong and i would suggest to figure out which one!

**Comment by marchermans** [comment]
Uploaded and aviablable to you

**Comment by marchermans** [comment]
Have you tested this Drako?
