### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by crozear** [SmithsGaming/Armory#34]
Sorry I don't check my github often and I really would like this to work, here is the complete crash log from start to finish, like I said earlier, whenever I put coal in the fire place it crashes. I'm really sorry for not checking up on the issue.
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 7/22/16 12:18 PM
Description: Updating screen events

java.lang.AbstractMethodError: com.smithsmodding.armory.common.tileentity.TileEntityFireplace.markDirty()V
    at com.smithsmodding.smithscore.common.inventory.IItemStorage$IInventoryWrapper.func_70296_d(IItemStorage.java:100)
    at net.minecraft.inventory.Slot.func_75218_e(Slot.java:78)
    at net.minecraft.inventory.Slot.func_75215_d(Slot.java:73)
    at net.minecraft.inventory.Container.func_184996_a(Container.java:191)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:550)
    at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:630)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:579)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:556)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:515)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at com.smithsmodding.smithscore.common.inventory.IItemStorage$IInventoryWrapper.func_70296_d(IItemStorage.java:100)
    at net.minecraft.inventory.Slot.func_75218_e(Slot.java:78)
    at net.minecraft.inventory.Slot.func_75215_d(Slot.java:73)
    at net.minecraft.inventory.Container.func_184996_a(Container.java:191)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:550)
    at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:630)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:579)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:556)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:515)

-- Affected screen --
Details:
    Screen name: com.smithsmodding.armory.client.gui.implementations.fireplace.GuiFireplace

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['Crozear'/184, l='MpServer', x=5.95, y=4.00, z=-1081.70]]
    Chunk stats: MultiplayerChunkCache: 527, 527
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (3,4,-1075), Chunk: (at 3,0,13 in 0,-68; contains blocks 0,0,-1088 to 15,255,-1073), Region: (0,-3; contains chunks 0,-96 to 31,-65, blocks 0,0,-1536 to 511,255,-1025)
    Level time: 2867 game time, 2867 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 89 total; [EntitySlime['Slime'/128, l='MpServer', x=71.98, y=4.00, z=-1125.68], EntitySlime['Slime'/129, l='MpServer', x=85.02, y=4.04, z=-1122.34], EntitySlime['Slime'/130, l='MpServer', x=82.49, y=4.55, z=-1107.89], EntitySheep['Sheep'/131, l='MpServer', x=74.62, y=4.00, z=-1102.67], EntityCow['Cow'/132, l='MpServer', x=64.61, y=4.00, z=-1059.18], EntitySlime['Slime'/133, l='MpServer', x=72.40, y=4.00, z=-1054.17], EntityCow['Cow'/134, l='MpServer', x=72.32, y=4.00, z=-1052.83], EntityChicken['Chicken'/135, l='MpServer', x=69.51, y=4.00, z=-1041.86], EntityChicken['Chicken'/136, l='MpServer', x=71.57, y=4.00, z=-1050.56], EntityChicken['Chicken'/137, l='MpServer', x=75.77, y=4.00, z=-1049.54], EntitySheep['Sheep'/138, l='MpServer', x=71.50, y=4.00, z=-1045.50], EntitySheep['Sheep'/139, l='MpServer', x=71.32, y=4.00, z=-1047.51], EntitySlime['Slime'/140, l='MpServer', x=76.11, y=5.17, z=-1048.55], EntityPig['Pig'/141, l='MpServer', x=84.52, y=4.00, z=-1152.63], EntitySheep['Sheep'/143, l='MpServer', x=85.37, y=4.00, z=-1150.28], EntitySheep['Sheep'/144, l='MpServer', x=80.91, y=4.00, z=-1145.83], EntitySlime['Slime'/153, l='MpServer', x=81.86, y=4.00, z=-1059.30], EntityChicken['Chicken'/159, l='MpServer', x=80.20, y=4.00, z=-1043.56], EntitySlime['Slime'/34, l='MpServer', x=-71.86, y=4.00, z=-1057.64], EntitySlime['Slime'/41, l='MpServer', x=-50.40, y=4.28, z=-1156.94], EntityChicken['Chicken'/42, l='MpServer', x=-51.17, y=4.00, z=-1112.38], EntitySlime['Slime'/43, l='MpServer', x=-64.87, y=4.00, z=-1029.70], EntitySlime['Slime'/44, l='MpServer', x=-64.28, y=4.95, z=-1021.64], EntitySlime['Slime'/48, l='MpServer', x=-41.54, y=4.17, z=-1128.74], EntitySlime['Slime'/49, l='MpServer', x=-30.94, y=4.42, z=-1127.97], EntityCow['Cow'/50, l='MpServer', x=-39.61, y=4.00, z=-1110.65], EntityCow['Cow'/51, l='MpServer', x=-41.50, y=4.00, z=-1108.50], EntityCow['Cow'/52, l='MpServer', x=-44.67, y=4.00, z=-1111.04], EntitySheep['Sheep'/53, l='MpServer', x=-43.58, y=4.00, z=-1115.27], EntitySheep['Sheep'/54, l='MpServer', x=-48.35, y=4.00, z=-1107.70], EntitySheep['Sheep'/55, l='MpServer', x=-41.50, y=4.00, z=-1105.50], EntitySheep['Sheep'/56, l='MpServer', x=-30.13, y=4.00, z=-1101.30], EntityCow['Cow'/57, l='MpServer', x=-37.47, y=4.00, z=-1095.17], EntitySheep['Sheep'/58, l='MpServer', x=-39.45, y=4.00, z=-1089.73], EntitySheep['Sheep'/59, l='MpServer', x=-40.50, y=4.00, z=-1090.50], EntityCow['Cow'/60, l='MpServer', x=-38.50, y=4.00, z=-1085.50], EntitySheep['Sheep'/61, l='MpServer', x=-34.50, y=4.00, z=-1039.50], EntitySheep['Sheep'/62, l='MpServer', x=-33.46, y=4.00, z=-1031.74], EntitySlime['Slime'/64, l='MpServer', x=-29.21, y=4.14, z=-1153.02], EntitySlime['Slime'/65, l='MpServer', x=-16.32, y=5.10, z=-1142.99], EntitySlime['Slime'/66, l='MpServer', x=-29.52, y=4.00, z=-1127.00], EntitySlime['Slime'/67, l='MpServer', x=-18.74, y=4.00, z=-1130.76], EntityCow['Cow'/68, l='MpServer', x=-28.84, y=4.00, z=-1099.76], EntitySlime['Slime'/69, l='MpServer', x=-22.02, y=4.00, z=-1104.78], EntityCow['Cow'/70, l='MpServer', x=-26.50, y=4.00, z=-1040.50], EntityCow['Cow'/71, l='MpServer', x=-29.50, y=4.00, z=-1037.50], EntityCow['Cow'/72, l='MpServer', x=-29.94, y=4.00, z=-1036.26], EntityChicken['Chicken'/73, l='MpServer', x=-28.80, y=4.00, z=-1038.47], EntityCow['Cow'/74, l='MpServer', x=-26.33, y=4.00, z=-1029.92], EntitySlime['Slime'/79, l='MpServer', x=-15.38, y=4.95, z=-1159.56], EntitySlime['Slime'/80, l='MpServer', x=-13.00, y=4.00, z=-1140.37], EntitySlime['Slime'/81, l='MpServer', x=-2.11, y=4.00, z=-1126.01], EntityPlayerSP['Crozear'/184, l='MpServer', x=5.95, y=4.00, z=-1081.70], EntitySlime['Slime'/85, l='MpServer', x=8.51, y=4.04, z=-1129.99], EntitySlime['Slime'/86, l='MpServer', x=12.30, y=4.00, z=-1119.76], EntitySlime['Slime'/87, l='MpServer', x=12.23, y=4.00, z=-1131.06], EntitySlime['Slime'/88, l='MpServer', x=10.80, y=5.17, z=-1139.23], EntitySlime['Slime'/89, l='MpServer', x=1.35, y=4.00, z=-1112.64], EntitySlime['Slime'/90, l='MpServer', x=-0.97, y=4.28, z=-1110.03], EntitySlime['Slime'/91, l='MpServer', x=15.55, y=4.00, z=-1109.81], EntitySlime['Slime'/96, l='MpServer', x=21.20, y=4.00, z=-1149.27], EntitySlime['Slime'/97, l='MpServer', x=21.60, y=4.28, z=-1126.00], EntitySlime['Slime'/98, l='MpServer', x=30.32, y=4.27, z=-1128.91], EntityChicken['Chicken'/99, l='MpServer', x=24.97, y=4.00, z=-1106.36], EntityCow['Cow'/100, l='MpServer', x=31.50, y=4.00, z=-1110.50], EntitySlime['Slime'/102, l='MpServer', x=33.97, y=4.55, z=-1149.78], EntitySlime['Slime'/103, l='MpServer', x=52.85, y=4.00, z=-1120.24], EntitySlime['Slime'/104, l='MpServer', x=31.28, y=4.00, z=-1125.63], EntityCow['Cow'/105, l='MpServer', x=38.33, y=4.00, z=-1123.17], EntityCow['Cow'/106, l='MpServer', x=34.29, y=4.00, z=-1111.58], EntityCow['Cow'/107, l='MpServer', x=33.19, y=4.00, z=-1113.85], EntityCow['Cow'/108, l='MpServer', x=33.50, y=4.00, z=-1107.50], EntityCow['Cow'/109, l='MpServer', x=39.16, y=4.00, z=-1114.60], EntitySlime['Slime'/110, l='MpServer', x=50.91, y=4.00, z=-1091.15], EntitySlime['Slime'/111, l='MpServer', x=45.37, y=4.00, z=-1099.15], EntitySlime['Slime'/112, l='MpServer', x=42.28, y=4.27, z=-1076.84], EntitySlime['Slime'/114, l='MpServer', x=56.95, y=4.00, z=-1127.13], EntitySlime['Slime'/115, l='MpServer', x=56.81, y=4.76, z=-1104.35], EntitySlime['Slime'/116, l='MpServer', x=62.05, y=4.42, z=-1114.58], EntitySlime['Slime'/117, l='MpServer', x=52.83, y=4.00, z=-1109.88], EntitySheep['Sheep'/118, l='MpServer', x=63.74, y=4.00, z=-1094.77], EntitySlime['Slime'/119, l='MpServer', x=62.34, y=4.27, z=-1098.99], EntitySlime['Slime'/120, l='MpServer', x=62.13, y=5.08, z=-1087.43], EntitySlime['Slime'/121, l='MpServer', x=61.05, y=5.17, z=-1087.99], EntityCow['Cow'/122, l='MpServer', x=62.50, y=4.00, z=-1049.50], EntitySlime['Slime'/123, l='MpServer', x=45.20, y=4.00, z=-1040.53], EntitySlime['Slime'/125, l='MpServer', x=73.83, y=4.00, z=-1134.44], EntityChicken['Chicken'/126, l='MpServer', x=68.77, y=4.00, z=-1110.32], EntityCow['Cow'/127, l='MpServer', x=68.83, y=4.00, z=-1108.69]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:414)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_92, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1003630328 bytes (957 MB) / 2412249088 bytes (2300 MB) up to 5726797824 bytes (5461 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.32 Powered by Forge 12.18.1.2014 10 mods loaded, 10 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.1.2014.jar) 
    UCHIJAAAA   Forge{12.18.1.2014} [Minecraft Forge](forge-1.10.2-12.18.1.2014.jar) 
    UCHIJAAAA   SmithsCore{1.10.2-1.2.0.0-200} [Smiths Core](smithscore-1.10.2-1.2.0.0-200.jar) 
    UCHIJAAAA   Armory{1.10.2-1.2.0.0-323} [Armory](armory-1.10.2-1.2.0.0-323.jar) 
    UCHIJAAAA   mantle{1.10-0.10.3.jenkins156} [Mantle](Mantle-1.10-0.10.3.jar) 
    UCHIJAAAA   tconstruct{1.10-2.3.3a.jenkins271} [Tinkers' Construct](TConstruct-1.10-2.3.3a.jar) 
    UCHIJAAAA   armory-weaponry{@VERSION@} [armory-weaponry](Armory-Weaponry-1.3.0-53.jar) 
    UCHIJAAAA   JEI{3.7.6.232} [Just Enough Items](jei_1.10.2-3.7.6.232.jar) 
    UCHIJAAAA   jeresources{0.4.6.41} [Just Enough Resources](JustEnoughResources-1.10.2-0.4.6.41.jar) 
    Loaded coremods (and transformers): 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 368.39' Renderer: 'GeForce GTX 980/PCIe/SSE2'
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)

```
Launched Version: forge-12.18.1.2014
LWJGL: 2.9.4
OpenGL: GeForce GTX 980/PCIe/SSE2 GL version 4.5.0 NVIDIA 368.39, NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 8x Intel(R) Core(TM) i7-3770K CPU @ 3.50G
```

Also, I really enjoyed this mod and played the 1.7.10 version and I think its a very good idea. You should keep up the work your doing on it. Hopefully you can add compatibility for other metals too like thaumium or dark steel and stuff like that.

**Comment by crozear** [comment]
Also I'm using the exact same setup as before in the last issue post.

**Comment by marchermans** [comment]
I fixed this already, you should just need to update to the latest Armory and SmithsCore versions to fix it. I had two methods with the same name,.

**Comment by crozear** [comment]
Didn't know you fixed it, I thought you needed the full log But whatever I guess

**Comment by marchermans** [comment]
Ah a different guys beat you to the punch, he delivered the log faster :D
