### ISSUE TITLE
JEI Bug

### ISSUE THREAD

**Issue by crozear** [SmithsGaming/Armory#35]
Whenever I look up the recipe in JEI for the stone furnace, it doesn't show up, it just shows how to make the iron and obsidian ones. Also an Idea is that whenever you craft things in a anvil it should retain the heat used to make it

**Comment by marchermans** [comment]
Actually, there is no recipe for the Stone Anvil. It is crafted in the World.

Make, out of 27 cobbelstone, a 3x3x3 cube of cobblestone.
Rightclick one of the four middle blocks on the side of the cube and it will form automatically.
