### ISSUE TITLE
Crashing with forge

### ISSUE THREAD

**Issue by Ravin890** [SmithsGaming/Armory#36]
Whenever a ingot is put into the forge (I mainly tested an iron ingot) that is not lit the client will crash. I am not sure if you were aware of this or not. Also I attached a crash report.
[crash-2016-09-09_23.31.01-server.txt](https://github.com/SmithsGaming/Armory/files/465211/crash-2016-09-09_23.31.01-server.txt)

Mods included are armory, armory - weaponry, just enough items, mantle, smithscore, and tconstruct

**Comment by marchermans** [comment]
So i tested this on my side and could not get it to crash, however, i can see a point were it might crash under certain conditions.

To verify this i would need the versions of the mods you mentioned above so i can rebuild your situation, i think either the OreDic integration registers a stack wrong or I messed up in Armory-Weaponry. To find that i need the exact versions of the mods.

Also is this a client or a dedi server crash?

**Comment by Ravin890** [comment]
the version of armory is 1.10.2-1.2.0.0-338
weaponry is 1.3.0-53
SmithsCore is 1.10.2-1.2.0.0-248
Also this is client (i don't know why it said server either with the crash report)

**Note: Decided to just test with just armory (same version), Just Enough items (1.10.2-3.9.0.248), and SmithsCore (same version) but got same crash.

**Comment by marchermans** [comment]
Hmm i can not seem to reproduce this, can you tell me exactly what you do?
Try reproducing this in creative only flat world, if it does happen there too, tell me what kind of metal you are putting in.

**Comment by marchermans** [comment]
Actually i am able to reproduce this
Will fix asap.

**Comment by Ravin890** [comment]
Lol okay.
