### ISSUE TITLE
Anvil Crafting Crash

### ISSUE THREAD

**Issue by CJL48** [SmithsGaming/Armory#39]
Putting in a valid recipe (or attempting to open the gui of an anvil that you put a valid recipe into) causes the game to crash.
[crash-2016-09-30_09.13.40-client.txt](https://github.com/SmithsGaming/Armory/files/503030/crash-2016-09-30_09.13.40-client.txt)
Versions:
Minecraft 1.10.2
Forge 12.18.1.2084
Armory 1.2.0.0-338
SmithsCore 1.2.0.0-251

**Comment by Ravin890** [comment]
Issue #36

**Comment by marchermans** [comment]
No this is not a duplicate

**Comment by Ravin890** [comment]
I had messed up and couldn't edit it and forgot to post i made a mistake

**Comment by marchermans** [comment]
No problem

**Comment by Ravin890** [comment]
I think I had same issue but forgot to mention that when I had the other post lol

**Comment by marchermans** [comment]
So i have been doing some debugging, and i cannot reproduce this. Please try to reproduce this with ONLY Armory and SmithsCore!

**Comment by CJL48** [comment]
Forgot about JEI. Even with JEI removed, crash still occurs. Which version are you trying to replicate the bug on?

**Comment by marchermans** [comment]
The latest

**Comment by CJL48** [comment]
If you look at the issue, you'll see that that is what I used.
EDIT: I'll try it with the latest smiths core.
Update: 1.2.1-257/259 Both crash on startup with latest armory and forge 12.18.2.2104.

**Comment by marchermans** [comment]
Noted thanks.

**Comment by CJL48** [comment]
Update: armory-1.10.2-1.2.0.0-353.jar no longer crashes when a recipe is in the anvil gui, but I've only able to craft fireplaces. That could be considered another issue.
Version info
armory 1.10.2-1.2.0.0-353
smithsCore 1.10.2-1.2.1-259
forge 1.10.2-12.18.2.2104

**Comment by marchermans** [comment]
Hmm
So zou can craft Fireplaces but nothing else in the GUI, does it crash if zou try something else?

**Comment by CJL48** [comment]
Not anymore

**Comment by marchermans** [comment]
So can you craft anything now? Or is it fixes?

**Comment by marchermans** [comment]
Seems to be fixed so closing.
