### ISSUE TITLE
Armory recipes not visible in JEI

### ISSUE THREAD

**Issue by Raycoms** [SmithsGaming/Armory#47]
I am unable to see the recipe for the armor and I can't click the recipe for the hammer to show it.

**Comment by marchermans** [comment]
Which version of Armory / JEI / Minecraft are you using?
Are you using a public modpack?

**Comment by Raycoms** [comment]
Minecraft 1.10, the newest version of armory and JEI on curse.
It's our own modpack on our server

2017-02-11 20:02 GMT-02:00 Orion <notifications@github.com>:

**Comment by marchermans** [comment]
Okey that is weird. I will take a look at this and the other crash you send in. However 1.10 development is actually closed. I am working on 1.11 instead.

**Comment by Raycoms** [comment]
We have a quite big modpack and servers and your mod combines very well
with our mod (Minecolonies) it would be great if we could use a working
version on our server.

2017-02-11 21:31 GMT-02:00 Orion <notifications@github.com>:

**Comment by marchermans** [comment]
So i did some digging. I tested the Minecolonies Testpack, and it seems that you are right.
I will take a look into JEI's API and try to find out why it does not load the API Implementation.

However i need to repair the 1.11 and the 1.10 branches to fix this. I hope that i can get this done this evening / tonight. If not i will try to produce a fix next Wednesday.

**Comment by Raycoms** [comment]
That would be great =) Glad to hear =)

2017-02-12 9:25 GMT-02:00 Orion <notifications@github.com>:

**Comment by marchermans** [comment]
@Raycoms are you the Minecolonies developer?

**Comment by Raycoms** [comment]
Yes I am one of the main developers of minecolonies.

2017-02-12 9:41 GMT-02:00 Orion <notifications@github.com>:

**Comment by marchermans** [comment]
Awesome. I tried finding out if you guys had an API, but could not find it. I would love to integrate Armory with minecolonies more. Kinda like i did with TiCon.

**Comment by Raycoms** [comment]
If your armory armors do implement the "armor" of minecraft our guards will
be able to use your armors without any problems.

We currently do not offer any integration API yet but we could work on that
if you're interested. What are you thinking about?

2017-02-12 9:56 GMT-02:00 Orion <notifications@github.com>:

**Comment by marchermans** [comment]
I am implementing ItemArmor so yeah that should work.
I was actually looking to add a nice new building for a Blacksmith who can in particularly make the armor for the guards.

**Comment by Raycoms** [comment]
That would be very interesting!

I could give you a complete guide on how to implement a worker in our case.
It's actually quite simple. Then we'd just activated/deactivated that
worker if your mod is activated together with ours.

2017-02-12 10:01 GMT-02:00 Orion <notifications@github.com>:

**Comment by marchermans** [comment]
That would be amazing, i would maybe even think about putting the 1.11 update back then to implement this. I loved this mod and it would be amazing if this would be possible.

**Comment by marchermans** [comment]
I was trying to find the source that you guys are using. But the Minecolonies/minecolonies development branch does not seem to hold the source for the mod.

**Comment by marvin-bitterlich** [comment]
@OrionDevelopment 

@Raycoms will write a more elaborate guide, but our `develop` branch contains the 1.10.2 sources of the mod. If you have any questions just ask

**Comment by Raycoms** [comment]
https://github.com/Minecolonies/minecolonies
Should hold the complete source.
https://github.com/Minecolonies/minecolonies/tree/develop/src/main/java/com/minecolonies/coremod
Here you will found all our sources.

To implement a worker you will need:

- A BlockHutArmorySmith.java which extends AbstractBlockHut.java -> this is
a classic minecraft block, you can add your own design/model/texture how
you think it is best. It will automatically inherit our GUI.
- A BuildingArmorySmith.java which extends AbstractWorkerBuilding.java.,
this is used to send data to the gui or to store related data persistent
over various sessions.
- A JobArmorySmith.java which extends AbstractJob.java. This contains
worker related data, things you want to store related to the worker, he
will lose this on death.

Now to the most important.

- A EntityAIWorkArmorySmith.java which extends AbstractEntityAIInteract
<JobArmorySmith>
Extending this you will get access to a lot of worker utils like
"walkToHut" which are quite helpful or request item handling which the
deliveryman might deliver or the worker will cry out to the player.

In "public enum AIState" you can define the stages your worker will have
like "waiting for material" or "smithing" or "cooldown" etc.

It's probably best to look at simple workers like the Deliveryman to check
out how we organize the AI code. But it's quite simple.

/**
 * Initialize the deliveryman and add all his tasks.
 *
 * @param deliveryman the job he has.
 */
public EntityAIWorkDeliveryman(@NotNull final JobDeliveryman deliveryman)
{
    super(deliveryman);
    super.registerTargets(
            /**
             * Check if tasks should be executed.
             */
            new AITarget(this::checkIfExecute, IDLE),
            new AITarget(IDLE, () -> START_WORKING),
            new AITarget(START_WORKING, this::checkWareHouse),
            new AITarget(PREPARE_DELIVERY, this::prepareDelivery),
            new AITarget(GATHER_IN_WAREHOUSE, this::gatherItemsFromWareHouse),
            new AITarget(DELIVERY, this::deliver),
            new AITarget(GATHERING, this::gather),
            new AITarget(DUMPING, this::dump)

    );
    worker.setSkillModifier(2 * worker.getCitizenData().getEndurance()
+ worker.getCitizenData().getCharisma());
    worker.setCanPickUpLoot(true);
}


In the Constructor you define a certain set of skill which is good for him
(to level up and gain perks like speed etc)
And you also define the transitions. After you set the AIStates of him you
can define to where they point.
In the example below, there are the states of the deliveryman. First, he
checks if he should execute at all and if yes he will continue to IDLE.
From IDLE he will directly go to START_WORKING and in the case of
START_WORKING he will call the method:


private AIState checkWareHouse()

And the return value of this method is the state he should go to next.
Quite simple, isn't it?

If you want to create a custom GUI you will need WindowHutArmorySmith.java
which extends AbstractWindowWorkerBuilding.java
and design your GUI as a XML in the assets.

I think that's all.


2017-02-12 10:16 GMT-02:00 Orion <notifications@github.com>:

**Comment by marchermans** [comment]
Nice! You guys have a MavenRepo i call pull the deobfed jar from? Or should i use the github source?

**Comment by Raycoms** [comment]
If you work at our repo we use travis to produce the jars and they land
here:
https://www.dropbox.com/sh/9cnqcjl0nan57cy/AAAlo6S1owxIw8tU_-7HJMHMa?dl=0

2017-02-12 15:08 GMT-02:00 Orion <notifications@github.com>:

**Comment by marchermans** [comment]
This should fix it once the build complete this. Do you guys have a IRC Channel or something we can communicate on so we can something like this going?

**Comment by marchermans** [comment]
Release for 1.2.0.0-395

**Comment by marvin-bitterlich** [comment]
@OrionDevelopment send me your email and I invite you to our slack channel :)

**Comment by marchermans** [comment]
Same mail as on my profile: oriondevelopment@outlook.com

**Comment by NullMagic** [comment]
This seems to be a problem again with the latest versions of JEI and Armory in 1.10, I know you're working on the 1.11 version (which I am looking forward to), but would it be possible to get a quick fix if it's not too much trouble?

**Comment by marchermans** [comment]
I will take a look
What is the exact issue?

**Comment by NullMagic** [comment]
Specifically it's not showing any of the recipes, making it rather difficult to progress in the mod.

**Comment by marchermans** [comment]
Hmm again. I will dig into it. The last time they changed api definitions mid mc version. Which screwed armory over

**Comment by NullMagic** [comment]
It appears this isn't actually a problem with JEI or Armory, it seems to be an issue with the Apple Core and Apple Skin mods, which for some reason cause it to not register in JEI fully, which I suppose means this should be a new issue, but I'm really not sure who I should send it to at this point.

**Comment by marchermans** [comment]
Hmm you say Apple Core he
